const productos = [
    {
        "id": 1,
        "producto": "Celular Samsung Galaxy A03",
        "precio":48000,
        "descripcion":"Celular Samsung Galaxy A03 Octa-Core/Pantalla 6.5″” HD+ Cam Pr 48Mp+2Mp/Cam Fr 5Mp 64Gb rom/4Gb ram/Bat 5000 mHa",
        "categoria": "Celular",
        "oferta":false,
    },{
        "id":2 ,
        "producto": "Celular Samsung Galaxy A13 128",
        "precio":70000,
        "descripcion":"Celular Samsung Galaxy A13 128 Octa-Core/Pantalla 6.6″” FHD+ Cam Pr 50Mp+5Mp+2Mp+2Mp Cam Fr 8Mp/128Gb rom/4Gb ram Bateria 5000 mHa",
        "categoria": "Celulares",
        "oferta":false,
    },{
        "id": 3,
        "producto": "Celular Samsung Galaxy A22 5G",
        "precio":60000,
        "descripcion":"Celular Samsung Galaxy A22 5G Octa-Core/Pantalla FHD 6.6″” Cam Pr48Mp+5Mp+2Mp/Cam Fr 8Mp 4Gb Ram/128Gb Rom/Bat 5000 mAh",
        "categoria": "Celulares",
        "oferta":true,
    },{
        "id": 4,
        "producto": "Monitor Giga 27″ Curvo Edge",
        "precio":130000,
        "descripcion":"Monitor Giga 27″ Curvo Edge FHD G27FC/165Hz",
        "categoria": "Monitores",
        "oferta":false,
    },{
        "id": 5,
        "producto": "Monitor led AOC G2790VX Gamer",
        "precio":85000,
        "descripcion":"Monitor led AOC G2790VX Gamer Pant 27″” FHD 144Hz VA panel Refrescp 1ms/FreeSync Premium Hdmi-DP",
        "categoria": "Monitores",
        "oferta":true,
    },{
        "id": 6,
        "producto": "Monitor led Hikvision 19″",
        "precio":30000,
        "descripcion":"Monitor led Hikvision 19″ DS-D5019QE-B/VGA-HDMI Resolucion 1366×768",
        "categoria": "Monitores",
        "oferta":true,
    },{
        "id": 7,
        "producto": "Impresora multif Brother T420W",
        "precio":150000,
        "descripcion":"Impresora multif Brother T420W Sistema continuo/Wi-Fi Insumos:BTD 5001 N/C/M/A Juego de botellas extra",
        "categoria": "Impresoras",
        "oferta":false,
    },{
        "id": 8,
        "producto": "Impresora multif HP 2775",
        "precio":25000,
        "descripcion":"Impresora multif HP 2775 Escaner/Copia/Imprime – Wi-Fi Insumos:667 negro/tricolor",
        "categoria": "Impresoras",
        "oferta":true,
    },{
        "id": 9,
        "producto": "Impresora multif HP 315",
        "precio":55000,
        "descripcion":"Impresora multif HP 315 Ink Tank/Insumos:GT51/52/53/54",
        "categoria": "Impresoras",
        "oferta":false,
    },{
        "id": 10,
        "producto": "Combo gamer Noga NKB-407 4en1",
        "precio":6000,
        "descripcion":"Combo gamer Noga NKB-407 4en1 Teclado y mouse retroiluminado Auricular gamer y pad",
        "categoria": "Teclados",
        "oferta":true,
    },{
        "id": 11,
        "producto": "Combo teclado y mouse Genius",
        "precio":3000,
        "descripcion":"Combo teclado y mouse Genius KM-8200 wireless",
        "categoria": "Teclados",
        "oferta":true,
    },{
        "id": 12,
        "producto": "Teclado mecanico Panter Rayden",
        "precio":16000,
        "descripcion":"Teclado mecanico Panter Rayden GKM302/Gamer/Retroiluminado RGB/Switch Blue",
        "categoria": "Teclados",
        "oferta":false,
    },{
        "id": 13,
        "producto": "Barra de sonido Monster GB301",
        "precio":13000,
        "descripcion":"Barra de sonido Monster GB301 Pot RMS 8w/Led RGB Conexión 3,5 mini plug, USB",
        "categoria": "Parlantes",
        "oferta":false,
    },{
        "id": 14,
        "producto": "Parlante Genius SP-Q160 Usb",
        "precio":2500,
        "descripcion":"Parlante Genius SP-Q160 Usb RMS 6W",
        "categoria": "Parlantes",
        "oferta":true,
    },{
        "id": 15,
        "producto": "Parlante Netmak NM-24 Siete",
        "precio":10000,
        "descripcion":"Parlante Netmak NM-24 Siete Bluetooth/6.5″”/Karaoke FM/USB/Led",
        "categoria": "Parlantes",
        "oferta":false,
    }
]